### ISSUE TITLE
Minecraft source code

### ISSUE THREAD

**Issue by Keridos** [SuperStarGamesNetwork/Pltypus-Mod-Source-Code#1]
You should really remove the Minecraft source code from this repo.

**Comment by R3alCl0ud** [comment]
this is(or was)  a working repository in which the mod was develeoped

**Comment by Keridos** [comment]
it still is illegal

**Comment by Keridos** [comment]
@RealCloudCraft You are aware that you are seriously violating the Minecraft EULA here? Mojang can sue you for this.

**Comment by R3alCl0ud** [comment]
not breaking eula, as its not the official source, and the code here is all open source

**Comment by R3alCl0ud** [comment]
also im not making money off of this, nor am I releasing an update to the game, nor am I making illegal copies of the game

**Comment by Keridos** [comment]
Out of the EULA of Mojangs Minecraft: "The one major rule is that you must not distribute anything we‘ve made." You are clearly breaching this one as you are in fact distributing the source code they wrote.

**Comment by diesieben07** [comment]
"I am not making money off of this" is not an excuse for copyright violation. Copyright violation is copyright violation. Whether you or your cat or your granddad is making money (or bananas) from it is irrelevant.

Edit: Oh, and by the way, this is not only against Mojang's EULA but also against MCP's Terms of Use.
